language: python

services:
  - xfb

matrix:
  include:
    - os: linux
      python: 3.6
      env: LINT=1
    - os: linux
      python: 3.7
      env: LINT=1
    - os: osx
      python: 3.6
      env: LINT=1
    - os: osx
      python: 3.7
      env: LINT=1

stages:
  - install
  - test
  - deploy

before install:
  - sudo apt-get install -qq libxkbcommon-x11-0

install:
  - pip install -r requirements-dev.txt

script:
  - coverage erase
  - coverage run -a --source ./sksurgeryvtk -m pytest -v -s ./tests
  - coverage report -m
  - if [ $LINT == 1 ]; then
    pylint --rcfile=tests/pylintrc sksurgeryvtk tests --extension-pkg-whitelist=vtk,cv2,PySide2
    fi

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_existing: true
  on:
    tags: true
    branch: master
