language: python

services:
  - xvfb

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: osx
      language: generic
      PYTHON_VER: py36

stages:
  - install
  - test
  - deploy

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libxkbcommon-x11-0; fi

install:
  - pip install -r requirements-dev.txt

script:
  - coverage erase
  - coverage run -a --source ./sksurgeryvtk -m pytest -v -s ./tests
  - coverage report -m
  - pylint --rcfile=tests/pylintrc sksurgeryvtk

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_existing: true
  on:
    tags: true
    branch: master
