on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install xvfb libxkbcommon-x11-0
          export QT_QPA_PLATFORM=xcb
          xvfb-run  -a python -m pytest -vv -s tests/test_basic_qt_vtk.py
